import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiMongodb,
  SiPostgresql,
  SiGit,
  SiDocker,
  SiFigma,
  SiGraphql,
  SiThreedotjs,
  SiSupabase,
  SiLaravel,
  SiPhp,
  SiBootstrap,
  SiExpress,
  SiVscodium,
  SiApache,
  SiMysql,
  SiSqlite,
} from "react-icons/si";
import { FaJava } from "react-icons/fa6";
import { Cloud, Database } from "lucide-react";
import type { IconType } from "react-icons";
import type { SkillIcon } from "../data/content";

export const skillIconMap: Record<SkillIcon, { Icon: IconType; color: string }> = {
  javascript: { Icon: SiJavascript, color: "#F0DB4F" },
  typescript: { Icon: SiTypescript, color: "#3178C6" },
  react: { Icon: SiReact, color: "#61DAFB" },
  nextjs: { Icon: SiNextdotjs, color: "#EDEDED" },
  nodejs: { Icon: SiNodedotjs, color: "#3C873A" },
  html5: { Icon: SiHtml5, color: "#E44D26" },
  css3: { Icon: SiCss, color: "#1572B6" },
  tailwind: { Icon: SiTailwindcss, color: "#38BDF8" },
  mongodb: { Icon: SiMongodb, color: "#4DB33D" },
  postgresql: { Icon: SiPostgresql, color: "#336791" },
  git: { Icon: SiGit, color: "#F05032" },
  docker: { Icon: SiDocker, color: "#2496ED" },
  aws: { Icon: Cloud as IconType, color: "#FF9900" },
  figma: { Icon: SiFigma, color: "#F24E1E" },
  graphql: { Icon: SiGraphql, color: "#E10098" },
  threejs: { Icon: SiThreedotjs, color: "#EDEDED" },
  supabase: { Icon: SiSupabase, color: "#3ECF8E" },
  laravel: { Icon: SiLaravel, color: "#FF2D20" },
  php: { Icon: SiPhp, color: "#777BB4" },
  bootstrap: { Icon: SiBootstrap, color: "#7952B3" },
  express: { Icon: SiExpress, color: "#EDEDED" },
  vscode: { Icon: SiVscodium, color: "#22A8F2" },
  apache: { Icon: SiApache, color: "#D22128" },
  java: { Icon: FaJava as IconType, color: "#5382A1" },
  mysql: { Icon: SiMysql, color: "#4479A1" },
  sqlite: { Icon: SiSqlite, color: "#003B57" },
  sqlyog: { Icon: Database as IconType, color: "#008080" },
};